
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\A\Documents\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1440x1024")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1024,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    1440.0,
    143.0,
    fill="#520000",
    outline="")

canvas.create_rectangle(
    89.0,
    196.0,
    635.0,
    742.0,
    fill="#EEEEEE",
    outline="")

canvas.create_rectangle(
    718.0,
    159.0,
    720.0,
    1001.0,
    fill="#520000",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    355.5,
    812.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#747474",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=110.0,
    y=790.0,
    width=491.0,
    height=42.0
)

canvas.create_text(
    110.0,
    770.0,
    anchor="nw",
    text="Pickup location:",
    fill="#000000",
    font=("Inter", 16 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    356.5,
    903.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#747474",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=111.0,
    y=881.0,
    width=491.0,
    height=42.0
)

canvas.create_text(
    110.0,
    861.0,
    anchor="nw",
    text="Dropoff location:",
    fill="#000000",
    font=("Inter", 16 * -1)
)

canvas.create_text(
    807.0,
    834.0,
    anchor="nw",
    text="Price:  100 pisos",
    fill="#000000",
    font=("Inter Medium", 36 * -1)
)

canvas.create_text(
    807.0,
    223.0,
    anchor="nw",
    text="Select Vehicle Type",
    fill="#000000",
    font=("Inter Bold", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1092.0,
    y=911.0,
    width=250.0,
    height=44.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=807.0,
    y=911.0,
    width=250.0,
    height=44.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=807.0,
    y=285.0,
    width=546.0,
    height=55.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=807.0,
    y=351.0,
    width=546.0,
    height=55.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=807.0,
    y=417.0,
    width=546.0,
    height=55.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=807.0,
    y=483.0,
    width=546.0,
    height=55.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=807.0,
    y=549.0,
    width=546.0,
    height=55.0
)

canvas.create_text(
    89.0,
    8.0,
    anchor="nw",
    text="Go-do",
    fill="#FFFFFF",
    font=("Jaro Regular", 128 * -1)
)

canvas.create_rectangle(
    807.0,
    648.0,
    1215.0,
    780.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
